language: rust

rust: 1.34.1

cache:
  - cargo
  - npm

before_install:
  - cargo install wasm-pack --version 0.8.1
  - nvm install 10.15.3
  - nvm use 10.15.3
  - npm install -g elm@0.19.0-no-deps

install:
  - npm install

script:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
  local_dir: dist