language: rust

rust: 1.34.1

cache:
  - cargo
  - npm

before_install:
  # only install wasm-pack if we haven't cached it already
  - '[ "$(wasm-pack -V)" == "wasm-pack 0.8.1" ] || cargo install wasm-pack --version 0.8.1 --force'

  - nvm install 10.15.3
  - nvm use 10.15.3
  - npm install -g elm@0.19.0-no-deps
  - npm install -g elm-test@0.19.0-rev6
  - npm install -g elm-format@0.8.1

install:
  - npm install

script:
  - elm-format . --validate
  - elm-test
  - npm run build


deploy:
  provider: pages
  skip_cleanup: true
  github_token: $UVDIILUBQYPWHENQJRWJBKVH
  keep_history: true
  on:
    branch: master
  local_dir: dist